name: Build EXE Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests psutil speedtest python-whois dnspython pillow matplotlib geopy folium

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --noconsole NetworkMaster.py

    - name: Upload Artifact (برای تست)
      uses: actions/upload-artifact@v2
      with:
        name: NetworkMaster-EXE
        path: dist/NetworkMaster.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/NetworkMaster.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
