name: Build NetworkMaster EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests psutil speedtest-cli python-whois dnspython pillow matplotlib geopy folium tk

    - name: Build with PyInstaller
      run: |
        # Create hook file for speedtest
        mkdir -p hooks
        echo "from PyInstaller.utils.hooks import collect_data_files" > hooks/hook-speedtest.py
        echo "datas = collect_data_files('speedtest')" >> hooks/hook-speedtest.py
        
        pyinstaller --onefile --noconsole --name NetworkMaster --additional-hooks-dir=hooks NetworkMaster.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: NetworkMaster-EXE
        path: dist/NetworkMaster.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/NetworkMaster.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
