name: Build NetworkMaster EXE

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g. v1.0, v2.0)

jobs:
  build:
    runs-on: windows-latest  # Windows required for PyInstaller

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests psutil speedtest-cli python-whois dnspython pillow matplotlib geopy folium tk

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --noconsole --name NetworkMaster NetworkMaster.py

    - name: Upload artifact (for testing)
      uses: actions/upload-artifact@v4
      with:
        name: NetworkMaster-EXE
        path: dist/NetworkMaster.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/NetworkMaster.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
